version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: roomfinder-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=huyho2004
      - MYSQL_DATABASE=RoomFinder
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    container_name: roomfinder-api
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/RoomFinder?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=huyho2004
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql-data: