spring:
  application:
    name: room-finder

  datasource:
    url: jdbc:mysql://localhost:3306/RoomFinder?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: huyho2004
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect