#spring:
#  application:
#    name: room-finder
#
#  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/RoomFinder?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
#    username: root
#    password: ""
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    show-sql: false
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect
#
#server:
#  port: 8080



spring:
  application:
    name: room-finder

  datasource:
    url: jdbc:mysql://localhost:3306/RoomFinder?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect